# 3-2張量運算

In [2]:
import torch

In [4]:
tensor = torch.tensor([[1,2]])
print(tensor)

tensor2 = torch.IntTensor([[1,2]])
print(tensor2)

tensor3 = torch.FloatTensor([[1,2]])
print(tensor3)

tensor4 = torch.LongTensor([[1,2]])
print(tensor4)


tensor([[1, 2]])
tensor([[1, 2]], dtype=torch.int32)
tensor([[1., 2.]])
tensor([[1, 2]])


In [6]:
# 四則運算

A = torch.tensor([[1,2,3],
                    [4,5,6]])
B = torch.tensor([[9,8,7],
                    [3,2,6]])

print(A+B)
print(A-B)
print(A*B)
print(A/B)

# 內積

a = torch.tensor([[1,2,3],
                  [4,5,6]])
b = torch.tensor([[9,8],
                  [2,6],
                  [3,7]])

print(a@b)

tensor([[10, 10, 10],
        [ 7,  7, 12]])
tensor([[-8, -6, -4],
        [ 1,  3,  0]])
tensor([[ 9, 16, 21],
        [12, 10, 36]])
tensor([[0.1111, 0.2500, 0.4286],
        [1.3333, 2.5000, 1.0000]])
tensor([[ 22,  41],
        [ 64, 104]])


In [8]:
# 只要顯示數值 可轉換為Numpy array : x.numpy()
import numpy as np
A = torch.tensor([[1,2,3],
                    [4,5,6]])
print(A.numpy())


[[1 2 3]
 [4 5 6]]


In [10]:
# Numpy -> Pytorch

array = np.array([[1,2]])

tensor = torch.from_numpy(array)
tensor

tensor([[1, 2]], dtype=torch.int32)

In [14]:
# 沿著特定軸加總，輸出維度會少一維 sum() in pytorch, resuce_sum in tensorflow
A = torch.tensor([[1,2,3],
                    [4,5,6]])
print(A.sum(axis=0))
print(A.sum(axis=1))

tensor([5, 7, 9])
tensor([ 6, 15])


In [19]:
# Sparse Matrix
# Tensorflow : 自動決定var在CPU或GPU上
# Pytorch : 需要手動指定 不允許一個var在CPU，另一個var在GPU上，進行運算會出現錯誤

# .to('cpu') or .to('cuda') or .to('cuda:0') or .to('cuda:1')

tensor_gpu = tensor.cuda()
print(tensor_gpu)

# 如果兩張GPU，可以指定哪一張
# tensor_gpu_2 = tensor_gpu.to('cuda:1')
# print(tensor_gpu_2)

# 如果要將GPU上的tensor轉回CPU
tensor_cpu = tensor_gpu.cpu()
print(tensor_cpu)


tensor([[1, 2]], device='cuda:0', dtype=torch.int32)
tensor([[1, 2]], dtype=torch.int32)


In [20]:
# CPU與GPU上的tensor不能直接進行運算，必須轉換成同一個device
tensor_cpu + tensor_gpu

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [23]:
# 改成如此即可正運算
tensor_gpu + tensor_cpu.cuda()

tensor([[2, 4]], device='cuda:0', dtype=torch.int32)

In [25]:
# 在擁有GPU及只有CPU的環境下皆可運行
device = 'cuda' if torch.cuda.is_available() else 'cpu'

tensor_gpu.to(device) + tensor_cpu.to(device)

tensor([[2, 4]], device='cuda:0', dtype=torch.int32)

In [27]:
# Sparse Matrix
# 需要設定值的位置，以及值

# define (row, col)
i = torch.LongTensor([[0,1,1],
                      [2,0,2]])
# define value
v = torch.FloatTensor([3,4,5])

# define shape (2,3), turn into sparse matrix
torch.sparse.FloatTensor(i,v,torch.Size([2,3])).to_dense()

C:\Users\a7234\AppData\Local\Temp\ipykernel_26696\444830190.py:11: UserWarning: torch.sparse.SparseTensor(indices, values, shape, *, device=) is deprecated.  Please use torch.sparse_coo_tensor(indices, values, shape, dtype=, device=). (Triggered internally at ..\torch\csrc\utils\tensor_new.cpp:607.)
  torch.sparse.FloatTensor(i,v,torch.Size([2,3])).to_dense()


tensor([[0., 0., 3.],
        [4., 0., 5.]])

In [28]:
# 稀疏矩陣運算寫法

a = torch.sparse.FloatTensor(i,v,torch.Size([2,3])) + \
    torch.sparse.FloatTensor(i,v,torch.Size([2,3]))
a.to_dense()

tensor([[ 0.,  0.,  6.],
        [ 8.,  0., 10.]])

In [30]:
# 在程式開頭可以直接設定
# 禁用GPU
import torch
import os

os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
# 檢查GPU及cuda toolkit是否存在
print(torch.cuda.is_available())

# 若有多張GPU 可指定使用哪一張
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0"

True
